# Generated by Django 3.2.12 on 2022-03-15 16:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('operation_type', models.CharField(choices=[('sum', 'Sum'), ('sub', 'Subtraction'), ('div', 'Division'), ('mul', 'Multiplication'), ('sqrt', 'Square root'), ('fact', 'Factorial')], max_length=4)),
                ('operands', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
